/***************************************************************************//**
* File Name: cycfg_gatt_db.h
*
* Description:
* Definitions for constants used in the device's GATT database and function
* prototypes.
* This file should not be modified. It was automatically generated by
* Bluetooth Configurator 2.60.0.1460
*
********************************************************************************
* Copyright 2023 Cypress Semiconductor Corporation (an Infineon company) or
* an affiliate of Cypress Semiconductor Corporation.
* SPDX-License-Identifier: Apache-2.0
*
* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
*     http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
*******************************************************************************/

#if !defined(CYCFG_GATT_DB_H)
#define CYCFG_GATT_DB_H

#include "stdint.h"

#define __UUID_SERVICE_GENERIC_ACCESS                          0x1800
#define __UUID_CHARACTERISTIC_DEVICE_NAME                      0x2A00
#define __UUID_CHARACTERISTIC_APPEARANCE                       0x2A01
#define __UUID_CHARACTERISTIC_PERIPHERAL_PREFERRED_CONNECTION_PARAMETERS    0x2A04
#define __UUID_SERVICE_GENERIC_ATTRIBUTE                       0x1801
#define __UUID_SERVICE_DEVICE_INFORMATION                      0x180A
#define __UUID_CHARACTERISTIC_PNP_ID                           0x2A50
#define __UUID_CHARACTERISTIC_FIRMWARE_REVISION_STRING         0x2A26
#define __UUID_SERVICE_SCAN_PARAMETERS                         0x1813
#define __UUID_CHARACTERISTIC_SCAN_INTERVAL_WINDOW             0x2A4F
#define __UUID_SERVICE_BATTERY                                 0x180F
#define __UUID_CHARACTERISTIC_BATTERY_LEVEL                    0x2A19
#define __UUID_DESCRIPTOR_CLIENT_CHARACTERISTIC_CONFIGURATION    0x2902
#define __UUID_DESCRIPTOR_REPORT_REFERENCE                     0x2908
#define __UUID_SERVICE_ATVS                                    0x64, 0xB6, 0x17, 0xF6, 0x01, 0xAF, 0x7D, 0xBC, 0x05, 0x4F, 0x21, 0x5A, 0x01, 0x00, 0x5E, 0xAB
#define __UUID_CHARACTERISTIC_ATVS_ATV_WRITE_CHAR              0x64, 0xB6, 0x17, 0xF6, 0x01, 0xAF, 0x7D, 0xBC, 0x05, 0x4F, 0x21, 0x5A, 0x02, 0x00, 0x5E, 0xAB
#define __UUID_CHARACTERISTIC_ATVS_ATV_READ_CHAR               0x64, 0xB6, 0x17, 0xF6, 0x01, 0xAF, 0x7D, 0xBC, 0x05, 0x4F, 0x21, 0x5A, 0x03, 0x00, 0x5E, 0xAB
#define __UUID_CHARACTERISTIC_ATVS_ATV_CONTROL_CHAR            0x64, 0xB6, 0x17, 0xF6, 0x01, 0xAF, 0x7D, 0xBC, 0x05, 0x4F, 0x21, 0x5A, 0x04, 0x00, 0x5E, 0xAB
#define __UUID_SERVICE_HUMAN_INTERFACE_DEVICE                  0x1812
#define __UUID_CHARACTERISTIC_PROTOCOL_MODE                    0x2A4E
#define __UUID_CHARACTERISTIC_HID_INFORMATION                  0x2A4A
#define __UUID_CHARACTERISTIC_HID_CONTROL_POINT                0x2A4C
#define __UUID_CHARACTERISTIC_REPORT                           0x2A4D
#define __UUID_CHARACTERISTIC_REPORT_MAP                       0x2A4B
#define __UUID_DESCRIPTOR_EXTERNAL_REPORT_REFERENCE            0x2907
#define __UUID_CHARACTERISTIC_SERVICE_CHANGED                  0x2A05

/* Service Generic Access */
#define HDLS_GAP                                               0x0001
/* Characteristic Device Name */
#define HDLC_GAP_DEVICE_NAME                                   0x0002
#define HDLC_GAP_DEVICE_NAME_VALUE                             0x0003
/* Characteristic Appearance */
#define HDLC_GAP_APPEARANCE                                    0x0004
#define HDLC_GAP_APPEARANCE_VALUE                              0x0005
/* Characteristic Peripheral Preferred Connection Parameters */
#define HDLC_GAP_PERIPHERAL_PREFERRED_CONNECTION_PARAMETERS    0x0006
#define HDLC_GAP_PERIPHERAL_PREFERRED_CONNECTION_PARAMETERS_VALUE    0x0007

/* Service Generic Attribute */
#define HDLS_GATT                                              0x0008

/* Service Device Information */
#define HDLS_DIS                                               0x0009
/* Characteristic PnP ID */
#define HDLC_DIS_PNP_ID                                        0x000A
#define HDLC_DIS_PNP_ID_VALUE                                  0x000B
/* Characteristic Firmware Revision String */
#define HDLC_DIS_FIRMWARE_REVISION_STRING                      0x000C
#define HDLC_DIS_FIRMWARE_REVISION_STRING_VALUE                0x000D

/* Service Scan Parameters */
#define HDLS_SCPS                                              0x000E
/* Characteristic Scan Interval Window */
#define HDLC_SCPS_SCAN_INTERVAL_WINDOW                         0x000F
#define HDLC_SCPS_SCAN_INTERVAL_WINDOW_VALUE                   0x0010

/* Service Battery */
#define HDLS_BAS                                               0x0011
/* Characteristic Battery Level */
#define HDLC_BAS_BATTERY_LEVEL                                 0x0012
#define HDLC_BAS_BATTERY_LEVEL_VALUE                           0x0013
/* Descriptor Client Characteristic Configuration */
#define HDLD_BAS_BATTERY_LEVEL_CLIENT_CHAR_CONFIG              0x0014
/* Descriptor Report Reference */
#define HDLD_BAS_BATTERY_LEVEL_REPORT_REFERENCE                0x0015

/* Service ATVS */
#define HDLS_ATVS                                              0x0016
/* Characteristic ATV_Write_Char */
#define HDLC_ATVS_ATV_WRITE_CHAR                               0x0017
#define HDLC_ATVS_ATV_WRITE_CHAR_VALUE                         0x0018
/* Characteristic ATV_Read_Char */
#define HDLC_ATVS_ATV_READ_CHAR                                0x0019
#define HDLC_ATVS_ATV_READ_CHAR_VALUE                          0x001A
/* Descriptor ATV_Read_CCCD */
#define HDLD_ATVS_ATV_READ_CHAR_ATV_READ_CCCD                  0x001B
/* Characteristic ATV_Control_Char */
#define HDLC_ATVS_ATV_CONTROL_CHAR                             0x001C
#define HDLC_ATVS_ATV_CONTROL_CHAR_VALUE                       0x001D
/* Descriptor ATV_Control_CCCD */
#define HDLD_ATVS_ATV_CONTROL_CHAR_ATV_CONTROL_CCCD            0x001E

/* Service Human Interface Device */
#define HDLS_HIDS                                              0x001F
/* Service Battery */
#define HDLI_HIDS_INCLUDE_BAS                                  0x0020
/* Characteristic Protocol Mode */
#define HDLC_HIDS_PROTOCOL_MODE                                0x0021
#define HDLC_HIDS_PROTOCOL_MODE_VALUE                          0x0022
/* Characteristic HID Information */
#define HDLC_HIDS_HID_INFORMATION                              0x0023
#define HDLC_HIDS_HID_INFORMATION_VALUE                        0x0024
/* Characteristic HID Control Point */
#define HDLC_HIDS_HID_CONTROL_POINT                            0x0025
#define HDLC_HIDS_HID_CONTROL_POINT_VALUE                      0x0026
/* Characteristic kbd_in_report */
#define HDLC_HIDS_KBD_IN_REPORT                                0x0027
#define HDLC_HIDS_KBD_IN_REPORT_VALUE                          0x0028
/* Descriptor Client Characteristic Configuration */
#define HDLD_HIDS_KBD_IN_REPORT_CLIENT_CHAR_CONFIG             0x0029
/* Descriptor Report Reference */
#define HDLD_HIDS_KBD_IN_REPORT_REPORT_REFERENCE               0x002A
/* Characteristic cc_in_report */
#define HDLC_HIDS_CC_IN_REPORT                                 0x002B
#define HDLC_HIDS_CC_IN_REPORT_VALUE                           0x002C
/* Descriptor Client Characteristic Configuration */
#define HDLD_HIDS_CC_IN_REPORT_CLIENT_CHAR_CONFIG              0x002D
/* Descriptor Report Reference */
#define HDLD_HIDS_CC_IN_REPORT_REPORT_REFERENCE                0x002E
/* Characteristic Report Map */
#define HDLC_HIDS_REPORT_MAP                                   0x002F
#define HDLC_HIDS_REPORT_MAP_VALUE                             0x0030
/* Descriptor External Report Reference */
#define HDLD_HIDS_REPORT_MAP_EXTERNAL_REPORT_REFERENCE         0x0031
/* HID Report Defines */
#define APP_HIDS_REPORT_MAP_USAGE_PAGE_0                    0x05
#define APP_HIDS_REPORT_MAP_USAGE_PAGE_0_VALUE              0x01
#define APP_HIDS_REPORT_MAP_USAGE_0                         0x09
#define APP_HIDS_REPORT_MAP_USAGE_0_VALUE                   0x06
#define APP_HIDS_REPORT_MAP_COLLECTION_0                    0xA1
#define APP_HIDS_REPORT_MAP_COLLECTION_0_VALUE              0x01
#define APP_HIDS_REPORT_MAP_USAGE_PAGE_1                    0x05
#define APP_HIDS_REPORT_MAP_USAGE_PAGE_1_VALUE              0x07
#define APP_HIDS_REPORT_MAP_REPORT_ID_0                     0x85
#define APP_HIDS_REPORT_MAP_REPORT_ID_0_VALUE               0x01
#define APP_HIDS_REPORT_MAP_REPORT_SIZE_0                   0x75
#define APP_HIDS_REPORT_MAP_REPORT_SIZE_0_VALUE             0x08
#define APP_HIDS_REPORT_MAP_REPORT_COUNT_0                  0x95
#define APP_HIDS_REPORT_MAP_REPORT_COUNT_0_VALUE            0x03
#define APP_HIDS_REPORT_MAP_LOGICAL_MINIMUM_0               0x15
#define APP_HIDS_REPORT_MAP_LOGICAL_MINIMUM_0_VALUE         0x00
#define APP_HIDS_REPORT_MAP_LOGICAL_MAXIMUM_0               0x25
#define APP_HIDS_REPORT_MAP_LOGICAL_MAXIMUM_0_VALUE         0xFF
#define APP_HIDS_REPORT_MAP_USAGE_MINIMUM_0                 0x19
#define APP_HIDS_REPORT_MAP_USAGE_MINIMUM_0_VALUE           0x00
#define APP_HIDS_REPORT_MAP_USAGE_MAXIMUM_0                 0x29
#define APP_HIDS_REPORT_MAP_USAGE_MAXIMUM_0_VALUE           0xFF
#define APP_HIDS_REPORT_MAP_INPUT_0                         0x81
#define APP_HIDS_REPORT_MAP_INPUT_0_VALUE                   0x00
#define APP_HIDS_REPORT_MAP_END_COLLECTION_0                0xC0
#define APP_HIDS_REPORT_MAP_USAGE_PAGE_2                    0x05
#define APP_HIDS_REPORT_MAP_USAGE_PAGE_2_VALUE              0x0C
#define APP_HIDS_REPORT_MAP_USAGE_1                         0x09
#define APP_HIDS_REPORT_MAP_USAGE_1_VALUE                   0x01
#define APP_HIDS_REPORT_MAP_COLLECTION_1                    0xA1
#define APP_HIDS_REPORT_MAP_COLLECTION_1_VALUE              0x01
#define APP_HIDS_REPORT_MAP_REPORT_ID_1                     0x85
#define APP_HIDS_REPORT_MAP_REPORT_ID_1_VALUE               0x02
#define APP_HIDS_REPORT_MAP_REPORT_SIZE_1                   0x75
#define APP_HIDS_REPORT_MAP_REPORT_SIZE_1_VALUE             0x0C
#define APP_HIDS_REPORT_MAP_REPORT_COUNT_1                  0x95
#define APP_HIDS_REPORT_MAP_REPORT_COUNT_1_VALUE            0x02
#define APP_HIDS_REPORT_MAP_LOGICAL_MINIMUM_1               0x15
#define APP_HIDS_REPORT_MAP_LOGICAL_MINIMUM_1_VALUE         0x00
#define APP_HIDS_REPORT_MAP_LOGICAL_MAXIMUM_1               0x26
#define APP_HIDS_REPORT_MAP_LOGICAL_MAXIMUM_1_VALUE         0xFF, 0x07
#define APP_HIDS_REPORT_MAP_USAGE_MINIMUM_1                 0x19
#define APP_HIDS_REPORT_MAP_USAGE_MINIMUM_1_VALUE           0x00
#define APP_HIDS_REPORT_MAP_USAGE_MAXIMUM_1                 0x2A
#define APP_HIDS_REPORT_MAP_USAGE_MAXIMUM_1_VALUE           0xFF, 0x07
#define APP_HIDS_REPORT_MAP_INPUT_1                         0x81
#define APP_HIDS_REPORT_MAP_INPUT_1_VALUE                   0x00
#define APP_HIDS_REPORT_MAP_END_COLLECTION_1                0xC0
#define APP_HIDS_REPORT_MAP_USAGE_PAGE_3                    0x05
#define APP_HIDS_REPORT_MAP_USAGE_PAGE_3_VALUE              0x0C
#define APP_HIDS_REPORT_MAP_USAGE_2                         0x09
#define APP_HIDS_REPORT_MAP_USAGE_2_VALUE                   0x01
#define APP_HIDS_REPORT_MAP_COLLECTION_2                    0xA1
#define APP_HIDS_REPORT_MAP_COLLECTION_2_VALUE              0x01
#define APP_HIDS_REPORT_MAP_REPORT_ID_2                     0x85
#define APP_HIDS_REPORT_MAP_REPORT_ID_2_VALUE               0x03
#define APP_HIDS_REPORT_MAP_USAGE_PAGE_4                    0x05
#define APP_HIDS_REPORT_MAP_USAGE_PAGE_4_VALUE              0x06
#define APP_HIDS_REPORT_MAP_USAGE_3                         0x09
#define APP_HIDS_REPORT_MAP_USAGE_3_VALUE                   0x20
#define APP_HIDS_REPORT_MAP_LOGICAL_MINIMUM_2               0x15
#define APP_HIDS_REPORT_MAP_LOGICAL_MINIMUM_2_VALUE         0x00
#define APP_HIDS_REPORT_MAP_LOGICAL_MAXIMUM_2               0x25
#define APP_HIDS_REPORT_MAP_LOGICAL_MAXIMUM_2_VALUE         0x64
#define APP_HIDS_REPORT_MAP_REPORT_SIZE_2                   0x75
#define APP_HIDS_REPORT_MAP_REPORT_SIZE_2_VALUE             0x08
#define APP_HIDS_REPORT_MAP_REPORT_COUNT_2                  0x95
#define APP_HIDS_REPORT_MAP_REPORT_COUNT_2_VALUE            0x01
#define APP_HIDS_REPORT_MAP_INPUT_2                         0x81
#define APP_HIDS_REPORT_MAP_INPUT_2_VALUE                   0x02
#define APP_HIDS_REPORT_MAP_END_COLLECTION_2                0xC0

/* External Lookup Table Entry */
typedef struct
{
    uint16_t handle;
    uint16_t max_len;
    uint16_t cur_len;
    uint8_t  *p_data;
} gatt_db_lookup_table_t;

/* External definitions */
extern const uint8_t  gatt_database[];
extern const uint16_t gatt_database_len;
extern gatt_db_lookup_table_t app_gatt_db_ext_attr_tbl[];
extern const uint16_t app_gatt_db_ext_attr_tbl_size;
extern uint8_t app_gap_device_name[];
extern const uint16_t app_gap_device_name_len;
extern uint8_t app_gap_appearance[];
extern const uint16_t app_gap_appearance_len;
extern uint8_t app_gap_peripheral_preferred_connection_parameters[];
extern const uint16_t app_gap_peripheral_preferred_connection_parameters_len;
extern uint8_t app_dis_pnp_id[];
extern const uint16_t app_dis_pnp_id_len;
extern uint8_t app_dis_firmware_revision_string[];
extern const uint16_t app_dis_firmware_revision_string_len;
extern uint8_t app_scps_scan_interval_window[];
extern const uint16_t app_scps_scan_interval_window_len;
extern uint8_t app_bas_battery_level[];
extern const uint16_t app_bas_battery_level_len;
extern uint8_t app_bas_battery_level_client_char_config[];
extern const uint16_t app_bas_battery_level_client_char_config_len;
extern uint8_t app_bas_battery_level_report_reference[];
extern const uint16_t app_bas_battery_level_report_reference_len;
extern uint8_t app_atvs_atv_write_char[];
extern const uint16_t app_atvs_atv_write_char_len;
extern uint8_t app_atvs_atv_read_char[];
extern const uint16_t app_atvs_atv_read_char_len;
extern uint8_t app_atvs_atv_read_char_atv_read_cccd[];
extern const uint16_t app_atvs_atv_read_char_atv_read_cccd_len;
extern uint8_t app_atvs_atv_control_char[];
extern const uint16_t app_atvs_atv_control_char_len;
extern uint8_t app_atvs_atv_control_char_atv_control_cccd[];
extern const uint16_t app_atvs_atv_control_char_atv_control_cccd_len;
extern uint8_t app_hids_protocol_mode[];
extern const uint16_t app_hids_protocol_mode_len;
extern uint8_t app_hids_hid_information[];
extern const uint16_t app_hids_hid_information_len;
extern uint8_t app_hids_hid_control_point[];
extern const uint16_t app_hids_hid_control_point_len;
extern uint8_t app_hids_kbd_in_report[];
extern const uint16_t app_hids_kbd_in_report_len;
extern uint8_t app_hids_kbd_in_report_client_char_config[];
extern const uint16_t app_hids_kbd_in_report_client_char_config_len;
extern uint8_t app_hids_kbd_in_report_report_reference[];
extern const uint16_t app_hids_kbd_in_report_report_reference_len;
extern uint8_t app_hids_cc_in_report[];
extern const uint16_t app_hids_cc_in_report_len;
extern uint8_t app_hids_cc_in_report_client_char_config[];
extern const uint16_t app_hids_cc_in_report_client_char_config_len;
extern uint8_t app_hids_cc_in_report_report_reference[];
extern const uint16_t app_hids_cc_in_report_report_reference_len;
extern uint8_t app_hids_report_map[];
extern const uint16_t app_hids_report_map_len;
extern uint8_t app_hids_report_map_external_report_reference[];
extern const uint16_t app_hids_report_map_external_report_reference_len;

#endif /* CYCFG_GATT_DB_H */
